//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HSTS_RecipeManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Recipe_Id { get; set; }
        public string Name { get; set; }
        public int Prep_Time { get; set; }
        public string Ingredients { get; set; }
        public string Methods { get; set; }
        public int Num_Serves { get; set; }
        public string Category { get; set; }
    }
}
